-- ============================================================================
-- Star Schema DDL — Windows Security Telemetry (Sysmon + Security + PowerShell + WFP)
-- Source: dadosdia1.json / dadosdia2.json (MITRE ATT&CK "dmevals" / APT29 eval, NDJSON)
-- Target: Gold layer of a medallion lakehouse.
-- Platform: ANSI SQL / PostgreSQL-compatible types (portable to Snowflake/Delta/Iceberg
--           with minor type-name substitution — kept generic on purpose, per instructions).
-- Companion doc: docs/schema/star_schema.md (grain, rationale, SCD strategy, ER diagram)
-- Design reference: KB data-modeling/patterns/star-schema.md, concepts/scd-types.md
-- ============================================================================
-- Conventions used throughout:
--   *_sk   = surrogate key (system-generated, stable join key)
--   *_nk   = natural key (business/source identifier)
--   -1     = reserved "Not Applicable / Unknown" member row on every dimension
--            (see docs/schema/star_schema.md §7) — fact FKs are NOT NULL, never bare NULL.
-- ============================================================================


-- ============================================================================
-- DIM_DATE — conformed, Type 0 (static/derived; no SCD; regenerable, never updated in place)
-- Grain: one row per calendar date.
-- Source: derived from UtcTime (canonical event time) date part. Not sourced from a single
--         raw field; generated by a calendar-date generator script covering the observed
--         range (2020-05-01 .. 2020-05-02) plus buffer.
-- ============================================================================
CREATE TABLE dim_date (
    date_sk         INT          NOT NULL,   -- YYYYMMDD, e.g. 20200502; -1900-01-01 sentinel = 19000101
    full_date       DATE         NOT NULL,
    day_of_week     VARCHAR(10)  NOT NULL,
    day_of_month    INT          NOT NULL,
    month_number    INT          NOT NULL,
    month_name      VARCHAR(10)  NOT NULL,
    quarter         INT          NOT NULL,
    year            INT          NOT NULL,
    is_weekend      BOOLEAN      NOT NULL,
    CONSTRAINT pk_dim_date PRIMARY KEY (date_sk),
    CONSTRAINT uq_dim_date_full_date UNIQUE (full_date)
);

-- Unknown/N-A member (should not be hit in practice — UtcTime observed on all sampled events)
INSERT INTO dim_date (date_sk, full_date, day_of_week, day_of_month, month_number, month_name, quarter, year, is_weekend)
VALUES (19000101, DATE '1900-01-01', 'Unknown', 1, 1, 'Unknown', 1, 1900, FALSE);
-- FIX L2: a PARSEABLE date outside the generated calendar range has no row here and would
-- orphan the fact (INNER JOIN drops it on a lakehouse target where FKs aren't enforced).
-- Load contract: (a) generate the calendar well beyond the known load window, AND
-- (b) the Silver->Gold date lookup must auto-insert any missing in-range date as a late-arriving
-- member (see medallion_architecture.md §6.4) rather than falling back to 19000101.


-- ============================================================================
-- DIM_TIME — conformed, Type 0 (static seed; 1 row per second-of-day; 86,400 rows)
-- Grain: one row per second of day (HH:MM:SS), independent of date, for time-of-day
--        pattern analysis (e.g. "activity outside business hours" security signal).
-- Source: not sourced from raw data directly; generated as a static reference table.
--         The full-precision timestamp is preserved separately on the fact
--         (fact_security_event.event_utc_time) — dim_time is a categorical slicer, not a
--         replacement for millisecond precision.
-- ============================================================================
CREATE TABLE dim_time (
    time_sk         INT          NOT NULL,   -- HHMMSS as INT, e.g. 143045; -1 = Unknown
    hour_24         SMALLINT     NOT NULL,
    minute          SMALLINT     NOT NULL,
    second          SMALLINT     NOT NULL,
    hour_12         SMALLINT     NOT NULL,
    am_pm           VARCHAR(2)   NOT NULL,
    day_part        VARCHAR(10)  NOT NULL,   -- 'night','morning','afternoon','evening'
    is_business_hours BOOLEAN    NOT NULL,   -- FIX L3: UTC-referenced (time_sk is derived from canonical UTC event_utc_time), convention 08:00-18:00 UTC. NOT host-local — do not read as local business hours; for multi-timezone hosts apply a per-host offset join at query time instead.
    CONSTRAINT pk_dim_time PRIMARY KEY (time_sk)
);

INSERT INTO dim_time (time_sk, hour_24, minute, second, hour_12, am_pm, day_part, is_business_hours)
VALUES (-1, -1, -1, -1, -1, 'NA', 'Unknown', FALSE);


-- ============================================================================
-- DIM_HOST — conformed, SCD Type 1 (overwrite; ~4 distinct hosts, reference-quality data)
-- Grain: one row per unique host observed emitting telemetry.
-- Source-to-target mapping:
--   Hostname (e.g. "SCRANTON.dmevals.local")  -> hostname_fqdn
--   parsed prefix of Hostname                  -> hostname_nk (natural key)
--   parsed suffix of Hostname                  -> domain_suffix
--   host (Logstash/NXLog shipper identity)      -> collector_host
--   port (shipper source port)                  -> collector_port
-- ============================================================================
CREATE TABLE dim_host (
    host_sk         BIGINT        NOT NULL,           -- FIX M5: deterministic hash surrogate = hash(hostname_nk); MERGE/upsert-safe, Iceberg-compatible (no IDENTITY)
    hostname_nk     VARCHAR(100)  NOT NULL,           -- natural key, e.g. 'SCRANTON'
    hostname_fqdn   VARCHAR(255)  NOT NULL,            -- e.g. 'SCRANTON.dmevals.local'
    domain_suffix   VARCHAR(255),                      -- e.g. 'dmevals.local'
    collector_host  VARCHAR(255),                      -- NXLog/Logstash shipper host, e.g. 'wec.internal.cloudapp.net'
    collector_port  INT,                                -- shipper source port, e.g. 60737
    _loaded_at      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_dim_host PRIMARY KEY (host_sk),
    CONSTRAINT uq_dim_host_nk UNIQUE (hostname_nk)
);

INSERT INTO dim_host (host_sk, hostname_nk, hostname_fqdn, domain_suffix, collector_host, collector_port)
VALUES (-1, 'UNKNOWN', 'UNKNOWN', NULL, NULL, NULL);


-- ============================================================================
-- DIM_USER — conformed, SCD Type 1, ROLE-PLAYING (subject_user_sk / target_user_sk on fact)
-- Grain: one row per unique identity (SID) observed. ~9-12 distinct users.
-- Source-to-target mapping (coalesced across sources at Silver layer):
--   UserID (Sysmon), SubjectUserSid (Security), RemoteUserID (WFP)  -> sid (preferred natural key)
--   User (Sysmon, "DOMAIN\name"), AccountName+Domain (Sysmon/PS),
--     SubjectUserName+SubjectDomainName (Security)                  -> account_name, domain
--   AccountType (Sysmon)                                             -> account_type
-- Note: TargetUserName/TargetDomainName/TargetUserSid (Security logon events, 4624/4625) map
--       to the SAME dim_user table via the fact's target_user_sk role, not a separate table.
-- ============================================================================
CREATE TABLE dim_user (
    user_sk         BIGINT        NOT NULL,             -- FIX M5: deterministic hash surrogate = hash(sid); MERGE/upsert-safe, Iceberg-compatible (no IDENTITY)
    sid             VARCHAR(184)  NOT NULL,             -- natural key; Windows SID string, e.g. 'S-1-5-21-...'
    account_name    VARCHAR(100),
    domain          VARCHAR(100),
    account_full_name VARCHAR(210),                      -- 'DOMAIN\account_name' convenience column
    account_type    VARCHAR(30),                          -- 'User','Machine','Wellknown group', etc.
    effective_from  TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,  -- Type 1 today; columns kept for future Type 2 upgrade (see doc §4.4)
    is_current      BOOLEAN       NOT NULL DEFAULT TRUE,
    _loaded_at      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_dim_user PRIMARY KEY (user_sk),
    CONSTRAINT uq_dim_user_sid UNIQUE (sid)
);

INSERT INTO dim_user (user_sk, sid, account_name, domain, account_full_name, account_type)
VALUES (-1, 'N/A', 'N/A', NULL, NULL, 'Unknown');


-- ============================================================================
-- DIM_PROCESS — conformed, SCD TYPE 2
-- Grain: one row = one known version of one process instance (ProcessGuid).
-- Rationale for Type 2 (not a generic "always version everything" choice): the SAME
-- ProcessGuid is observed incrementally with different attribute completeness across
-- EventIDs (full detail only at EventID 1); a new version row per enriching sighting
-- creates an auditable "what did we know, and when" trail, and surfaces attribute
-- conflicts (e.g. Image path mismatch for the same ProcessGuid) as a security signal
-- instead of silently overwriting them. See docs/schema/star_schema.md §4.5.
--
-- Source-to-target mapping:
--   ProcessGuid                                  -> process_guid (natural key)
--   ProcessId                                    -> process_id (informational only, NOT a key — PIDs are recycled by the OS)
--   Image                                        -> image_path (+ parsed image_name)
--   Hashes ("SHA1=..,MD5=..,SHA256=..,IMPHASH=..") -> hash_sha1, hash_md5, hash_sha256, hash_imphash (parsed)
--   CommandLine                                  -> command_line
--   CurrentDirectory                              -> current_directory
--   IntegrityLevel                                -> integrity_level
--   Company, Product, Description,
--     OriginalFileName, FileVersion               -> company, product, description, original_file_name, file_version
--   ParentProcessGuid, ParentImage,
--     ParentProcessId, ParentCommandLine           -> parent_process_guid, parent_image, parent_process_id, parent_command_line
--   LogonGuid, TerminalSessionId                   -> logon_guid, terminal_session_id
--   (EventID that produced this version)           -> record_source
-- ============================================================================
CREATE TABLE dim_process (
    process_sk          BIGINT        NOT NULL,          -- FIX M5: deterministic hash surrogate = hash(process_guid, effective_from); unique per SCD2 version, MERGE/upsert- & rerun-safe, Iceberg-compatible (no IDENTITY)
    process_guid         VARCHAR(38)   NOT NULL,          -- natural key (not unique alone across SCD2 versions)
    process_id            BIGINT,                          -- PID at time of this version; informational only
    image_path            VARCHAR(500),
    image_name            VARCHAR(260),                    -- derived basename of image_path
    company                VARCHAR(200),
    product                VARCHAR(200),
    description            VARCHAR(500),
    original_file_name     VARCHAR(260),
    file_version            VARCHAR(100),
    command_line             VARCHAR(4000),
    current_directory         VARCHAR(500),
    integrity_level            VARCHAR(20),
    hash_sha1                   CHAR(40),
    hash_md5                     CHAR(32),
    hash_sha256                   CHAR(64),
    hash_imphash                   CHAR(32),
    parent_process_guid              VARCHAR(38),           -- text linkage only; not a hard FK (parent row may not be loaded yet — late-arriving dimension)
    parent_process_id                 BIGINT,
    parent_image                       VARCHAR(500),
    parent_command_line                  VARCHAR(4000),
    logon_guid                            VARCHAR(38),
    terminal_session_id                    VARCHAR(10),
    record_source                           VARCHAR(20) NOT NULL,  -- EventID that produced this version, e.g. '1','10','11'
    effective_from                          TIMESTAMP   NOT NULL,
    effective_to                             TIMESTAMP   NOT NULL DEFAULT TIMESTAMP '9999-12-31 00:00:00',
    is_current                                BOOLEAN    NOT NULL DEFAULT TRUE,
    _loaded_at                                 TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_dim_process PRIMARY KEY (process_sk),
    CONSTRAINT uq_dim_process_guid_version UNIQUE (process_guid, effective_from)
);

-- FIX C2: fact.process_sk MUST be resolved by a POINT-IN-TIME join
--   dim_process.process_guid = <event process_guid>
--   AND <event_utc_time> BETWEEN effective_from AND effective_to
-- (NOT is_current = TRUE — that misattributes historical events to a later, possibly
--  masquerading, Image-path version and defeats the §4.5 conflict-detection rationale).
-- This range index supports that as-of-event-time lookup; the is_current partial index is
-- retained only for the "latest known state" convenience view, never for fact FK resolution.
CREATE INDEX ix_dim_process_pit ON dim_process (process_guid, effective_from, effective_to);
CREATE INDEX ix_dim_process_current ON dim_process (process_guid) WHERE is_current = TRUE;

INSERT INTO dim_process (process_sk, process_guid, record_source, effective_from)
VALUES (-1, 'N/A', 'N/A', TIMESTAMP '1900-01-01 00:00:00');

-- FIX M4: joining fact -> dim_process on the NATURAL key (process_guid) fans out across every
-- SCD2 version and multiplies row counts. Two safe patterns only:
--   1. fact.process_sk = dim_process.process_sk        (exact version at event time; preferred)
--   2. ad-hoc natural-key joins go through this pre-filtered current-version view, never the base table:
CREATE VIEW dim_process_current AS
    SELECT * FROM dim_process WHERE is_current = TRUE;


-- ============================================================================
-- DIM_NETWORK_ENDPOINT — conformed, SCD Type 1, ROLE-PLAYING (source/destination on fact)
-- Grain: one row per unique IP address observed. Sparse fact usage (~0.4-0.6% of rows)
-- but conformed/reused across NetworkConnect (Sysmon EventID 3) and WFP (5156/5158/5447).
-- Deliberately excludes port (kept as degenerate fact column — see doc §4.6: source ports
-- are ephemeral/high-cardinality and don't belong on a dimension).
--
-- Source-to-target mapping:
--   SourceIp / SourceAddress (WFP)               -> ip_address (role: source)
--   DestinationIp / DestAddress (WFP)             -> ip_address (role: destination)
--   SourceIsIpv6 / DestinationIsIpv6              -> is_ipv6
--   SourceHostname / DestinationHostname          -> hostname (always empty in current data; retained for future DNS enrichment)
-- ============================================================================
CREATE TABLE dim_network_endpoint (
    endpoint_sk     BIGINT        NOT NULL,             -- FIX M5: deterministic hash surrogate = hash(ip_address); MERGE/upsert-safe, Iceberg-compatible (no IDENTITY)
    ip_address      VARCHAR(45)   NOT NULL,             -- natural key; VARCHAR(45) covers IPv6 (display form)
    is_ipv6         BOOLEAN       NOT NULL DEFAULT FALSE,
    ip_numeric      NUMERIC(39,0),                       -- FIX M3: numeric IP for CIDR/range scans (IPv4 -> 32-bit int; IPv6 -> 128-bit); populated at load, NULL only for -1 member
    ip_prefix_24    VARCHAR(15),                          -- FIX M3: precomputed /24 (IPv4) for common SOC subnet filters, e.g. '10.0.0'
    hostname        VARCHAR(255),                        -- DNS reverse-resolution, nullable (sparse/empty in current data)
    ip_class        VARCHAR(20),                          -- 'private','public','loopback','link_local' (derived at load time)
    _loaded_at      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_dim_network_endpoint PRIMARY KEY (endpoint_sk),
    -- FIX L1: NK is ip_address alone (a dotted-quad string is never valid IPv6 notation, so
    -- is_ipv6 is derivable and adds no disambiguation) — DDL and doc now agree on single-column NK.
    CONSTRAINT uq_dim_network_endpoint_ip UNIQUE (ip_address)
);

INSERT INTO dim_network_endpoint (endpoint_sk, ip_address, is_ipv6, ip_numeric, ip_prefix_24, hostname, ip_class)
VALUES (-1, 'N/A', FALSE, NULL, NULL, NULL, 'unknown');


-- ============================================================================
-- DIM_EVENT_TYPE — junk/reference dimension, Type 0 (static seed, no SCD)
-- Grain: one row per (EventID, Channel) combination. ~23 distinct combinations.
-- Source-to-target mapping:
--   EventID                -> event_id
--   Channel                -> channel
--   SourceName              -> source_name
--   Task                     -> task
--   (derived from Channel)   -> log_source ('sysmon'|'windows_security'|'powershell'|'wfp')
--   (derived from EventID + Message header, curated once) -> event_category, event_name
-- ============================================================================
CREATE TABLE dim_event_type (
    event_type_sk   INT           NOT NULL,             -- deterministic small-int seed key
    event_id        INT           NOT NULL,
    channel         VARCHAR(80)   NOT NULL,
    source_name     VARCHAR(80),
    task            INT,
    log_source      VARCHAR(20)   NOT NULL,               -- 'sysmon','windows_security','powershell','wfp'
    event_category  VARCHAR(50)   NOT NULL,                -- e.g. 'process_create','network_connect','registry_set_value'
    event_name      VARCHAR(150)  NOT NULL,                 -- human-readable label, e.g. 'Process Create'
    CONSTRAINT pk_dim_event_type PRIMARY KEY (event_type_sk),
    CONSTRAINT uq_dim_event_type_id_channel UNIQUE (event_id, channel)
);

-- Unknown/N-A member (FIX H2): a previously-unseen (EventID, Channel) combination is an
-- expected, non-blocking event per Silver DQ rule #2 (event_id_in_valid_set, warning@0.999),
-- so unresolved rows must land on -1 instead of failing the NOT NULL/REFERENCES or being
-- silently dropped by an INNER-JOIN lookup. Mirrors the -1 convention on every other dimension.
INSERT INTO dim_event_type (event_type_sk, event_id, channel, source_name, task, log_source, event_category, event_name)
VALUES (-1, -1, 'UNKNOWN', NULL, NULL, 'unknown', 'unknown', 'Unknown/Unmapped Event Type');

-- Representative seed rows (full ~23-row seed script maintained alongside Silver-layer ETL;
-- shown here to document the intended content/grain, not exhaustive).
INSERT INTO dim_event_type (event_type_sk, event_id, channel, source_name, task, log_source, event_category, event_name) VALUES
    (1,  1,    'Microsoft-Windows-Sysmon/Operational', 'Microsoft-Windows-Sysmon', 1,  'sysmon', 'process_create',            'Process Create'),
    (2,  3,    'Microsoft-Windows-Sysmon/Operational', 'Microsoft-Windows-Sysmon', 3,  'sysmon', 'network_connect',           'Network Connection Detected'),
    (3,  7,    'Microsoft-Windows-Sysmon/Operational', 'Microsoft-Windows-Sysmon', 7,  'sysmon', 'image_load',                'Image Loaded'),
    (4,  8,    'Microsoft-Windows-Sysmon/Operational', 'Microsoft-Windows-Sysmon', 8,  'sysmon', 'create_remote_thread',      'Create Remote Thread'),
    (5,  10,   'Microsoft-Windows-Sysmon/Operational', 'Microsoft-Windows-Sysmon', 10, 'sysmon', 'process_access',            'Process Accessed'),
    (6,  11,   'Microsoft-Windows-Sysmon/Operational', 'Microsoft-Windows-Sysmon', 11, 'sysmon', 'file_create',               'File Created'),
    (7,  12,   'Microsoft-Windows-Sysmon/Operational', 'Microsoft-Windows-Sysmon', 12, 'sysmon', 'registry_create_delete',    'Registry Object Added/Deleted'),
    (8,  13,   'Microsoft-Windows-Sysmon/Operational', 'Microsoft-Windows-Sysmon', 13, 'sysmon', 'registry_set_value',        'Registry Value Set'),
    (9,  22,   'Microsoft-Windows-Sysmon/Operational', 'Microsoft-Windows-Sysmon', 22, 'sysmon', 'dns_query',                 'DNS Query'),
    (10, 23,   'Microsoft-Windows-Sysmon/Operational', 'Microsoft-Windows-Sysmon', 23, 'sysmon', 'file_delete',               'File Delete'),
    (11, 4624, 'Security', 'Microsoft-Windows-Security-Auditing', 12544, 'windows_security', 'logon',                        'An Account Was Successfully Logged On'),
    (12, 4625, 'Security', 'Microsoft-Windows-Security-Auditing', 12544, 'windows_security', 'logon_failure',                'An Account Failed To Log On'),
    (13, 4656, 'Security', 'Microsoft-Windows-Security-Auditing', 12800, 'windows_security', 'object_access_request',        'A Handle To An Object Was Requested'),
    (14, 4658, 'Security', 'Microsoft-Windows-Security-Auditing', 12801, 'windows_security', 'object_handle_close',          'The Handle To An Object Was Closed'),
    (15, 4663, 'Security', 'Microsoft-Windows-Security-Auditing', 12801, 'windows_security', 'object_access',                'An Attempt Was Made To Access An Object'),
    (16, 4688, 'Security', 'Microsoft-Windows-Security-Auditing', 13312, 'windows_security', 'process_create_security',      'A New Process Has Been Created'),
    (17, 4690, 'Security', 'Microsoft-Windows-Security-Auditing', 12802, 'windows_security', 'object_handle_duplicate',      'An Attempt Was Made To Duplicate A Handle'),
    (18, 4703, 'Security', 'Microsoft-Windows-Security-Auditing', 13314, 'windows_security', 'token_privilege_adjust',       'A User Right Was Adjusted'),
    (19, 800,  'Windows PowerShell', 'PowerShell', 8, 'powershell', 'pipeline_execution',                                    'Pipeline Execution Details'),
    (20, 4103, 'Microsoft-Windows-PowerShell/Operational', 'Microsoft-Windows-PowerShell', 106, 'powershell', 'module_logging', 'Module Logging'),
    (21, 4104, 'Microsoft-Windows-PowerShell/Operational', 'Microsoft-Windows-PowerShell', 2,   'powershell', 'script_block_logging', 'Creating Scriptblock Text'),
    (22, 5156, 'Security', 'Microsoft-Windows-Security-Auditing', 12810, 'wfp', 'wfp_connection_permit',                     'WFP Permitted A Connection'),
    (23, 5158, 'Security', 'Microsoft-Windows-Security-Auditing', 12811, 'wfp', 'wfp_bind',                                  'WFP Permitted A Bind To A Local Port'),
    (24, 5447, 'Security', 'Microsoft-Windows-Security-Auditing', 13314, 'wfp', 'wfp_filter_change',                        'A Windows Filtering Platform Filter Was Changed');


-- ============================================================================
-- FACT_SECURITY_EVENT
-- Grain: one row = one raw security telemetry event = one line in the source NDJSON =
--        one Windows Event Log record (one RecordNumber within one Channel on one Hostname).
-- Factless fact table (event-occurrence grain; no additive numeric measure beyond the
-- implicit occurrence count — see docs/schema/star_schema.md §1).
--
-- Natural key / idempotency key for Silver->Gold upsert:
--   (source_file, hostname_nk, channel, record_number)
-- ============================================================================
CREATE TABLE fact_security_event (
    event_sk                 BIGINT        NOT NULL,     -- FIX M5: deterministic hash surrogate = hash(source_file, hostname_nk, channel, record_number) = the dedup NK; MERGE/rerun-idempotent, Iceberg-compatible (no IDENTITY)

    -- ---- Degenerate dimension / dedup natural key -------------------------
    source_file               VARCHAR(20)   NOT NULL,     -- 'dadosdia1' | 'dadosdia2' -- maps to: (source NDJSON file, lineage only)
    hostname_nk                VARCHAR(100)  NOT NULL,     -- maps to: Hostname (parsed short name; also drives host_sk join)
    channel                     VARCHAR(80)   NOT NULL,     -- maps to: Channel. WARNING (FIX M1): channel='Security' also covers WFP (5156/5158/5447), NOT just Windows auditing. To filter by true source use log_source below, never channel.
    log_source                   VARCHAR(20)   NOT NULL DEFAULT 'unknown', -- FIX M1: denormalized from dim_event_type.log_source ('sysmon'|'windows_security'|'powershell'|'wfp'|'unknown'); derived from EventID ranges at Silver, safe for direct fact filtering
    record_number                 BIGINT        NOT NULL,    -- maps to: RecordNumber

    -- ---- Conformed dimension FKs (NOT NULL, -1 default; see doc §7) -------
    date_sk                        INT           NOT NULL DEFAULT 19000101 REFERENCES dim_date(date_sk),
    time_sk                         INT           NOT NULL DEFAULT -1      REFERENCES dim_time(time_sk),
    host_sk                          BIGINT        NOT NULL DEFAULT -1      REFERENCES dim_host(host_sk),
    subject_user_sk                   BIGINT        NOT NULL DEFAULT -1      REFERENCES dim_user(user_sk),
    target_user_sk                     BIGINT        NOT NULL DEFAULT -1      REFERENCES dim_user(user_sk),      -- role-playing: logon target account (4624/4625 only)
    process_sk                          BIGINT        NOT NULL DEFAULT -1      REFERENCES dim_process(process_sk), -- role-playing: "acting" process (Sysmon-channel only; see doc §6.3)
    target_process_sk                    BIGINT        NOT NULL DEFAULT -1      REFERENCES dim_process(process_sk), -- role-playing: "acted upon" process (EventID 8/10 only)
    source_endpoint_sk                    BIGINT        NOT NULL DEFAULT -1      REFERENCES dim_network_endpoint(endpoint_sk),
    destination_endpoint_sk                BIGINT        NOT NULL DEFAULT -1      REFERENCES dim_network_endpoint(endpoint_sk),
    event_type_sk                           INT           NOT NULL DEFAULT -1      REFERENCES dim_event_type(event_type_sk), -- FIX H2: -1 = unknown/unmapped (EventID,Channel)

    -- ---- Canonical event time (full precision; see doc §6) -----------------
    event_utc_time                           TIMESTAMP     NOT NULL,             -- maps to: UtcTime (canonical)
    event_local_time                          TIMESTAMP,                         -- maps to: EventTime (collector-local; QA/skew only)
    ingest_event_time                          TIMESTAMP,                        -- maps to: @timestamp (Logstash ingest; pipeline-latency QA)
    event_received_time                         TIMESTAMP,                       -- maps to: EventReceivedTime (NXLog receipt; pipeline-latency QA)

    -- ---- Factless-fact convention measure -----------------------------------
    event_count                                  SMALLINT      NOT NULL DEFAULT 1,

    -- ---- File attributes (EventID 11, 23) -----------------------------------
    target_filename                               VARCHAR(1000),                 -- maps to: TargetFilename
    file_creation_utc_time                         TIMESTAMP,                    -- maps to: CreationUtcTime (EventID 11)
    file_is_executable                              BOOLEAN,                     -- maps to: IsExecutable (EventID 23)
    file_archived                                    BOOLEAN,                    -- maps to: Archived (EventID 23)

    -- ---- Registry attributes (EventID 12, 13, 4663 Key objects) -------------
    registry_target_object                            VARCHAR(1000),             -- maps to: TargetObject
    registry_details                                   VARCHAR(2000),            -- maps to: Details (EventID 13)
    registry_action                                     VARCHAR(20),             -- maps to: EventType sub-value embedded in Message (CreateKey/DeleteKey/SetValue)

    -- ---- Process access / injection attributes (EventID 8, 10) --------------
    granted_access                                       VARCHAR(20),            -- maps to: GrantedAccess (hex)
    call_trace                                            VARCHAR(4000),         -- maps to: CallTrace
    source_thread_id                                       INT,                  -- maps to: SourceThreadId
    target_thread_id                                        INT,                 -- maps to: TargetThreadId
    new_thread_id                                            INT,                -- maps to: NewThreadId (EventID 8)

    -- ---- DNS attributes (EventID 22) -----------------------------------------
    dns_query_name                                            VARCHAR(500),      -- maps to: QueryName
    dns_query_status                                           VARCHAR(10),      -- maps to: QueryStatus
    dns_query_results                                           VARCHAR(2000),   -- maps to: QueryResults (';'-delimited; candidate for future bridge table)

    -- ---- Object access / Security auditing (4656, 4658, 4663, 4690, 4703) ---
    object_name                                                  VARCHAR(1000),  -- maps to: ObjectName
    object_type                                                   VARCHAR(50),   -- maps to: ObjectType
    handle_id                                                      VARCHAR(20),  -- maps to: HandleId
    access_mask                                                     VARCHAR(20), -- maps to: AccessMask
    access_list                                                      VARCHAR(500), -- maps to: AccessList

    -- ---- Logon attributes (4624, 4625) ---------------------------------------
    logon_type                                                        INT,       -- maps to: LogonType
    logon_id                                                           VARCHAR(20), -- maps to: TargetLogonId
    authentication_package                                              VARCHAR(50), -- maps to: AuthenticationPackageName
    elevated_token                                                       BOOLEAN, -- maps to: ElevatedToken (decoded from '%%1842'-style Windows message code)
    workstation_name                                                      VARCHAR(100), -- maps to: WorkstationName

    -- ---- PowerShell attributes (800, 4103, 4104) ------------------------------
    script_block_text                                                      VARCHAR(8000), -- maps to: ScriptBlockText (see doc §5.1 re: extension-table option)
    script_block_id                                                         VARCHAR(38),  -- maps to: ScriptBlockId
    message_number                                                           INT,         -- maps to: MessageNumber
    message_total                                                             INT,        -- maps to: MessageTotal

    -- ---- Network attributes (EventID 3, 5156, 5158, 5447; ~0.5% density) ------
    source_port                                                                INT,        -- maps to: SourcePort
    destination_port                                                            INT,       -- maps to: DestinationPort | DestPort
    network_protocol                                                             VARCHAR(10), -- maps to: Protocol (Sysmon text 'tcp'/'udp' | WFP numeric '6'/'17', normalized)
    network_direction                                                             VARCHAR(10), -- maps to: Initiated (Sysmon bool) | Direction (WFP '%%code', normalized to 'inbound'/'outbound')
    network_action                                                                 VARCHAR(10), -- maps to: EventID 5156='allowed' | 5157(not in this dataset)='blocked'

    -- ---- Security-channel process fallback (no ProcessGuid available; see doc §6.3) --
    -- FIX H1: PID columns hold Silver's NORMALIZED decimal BIGINT (both Sysmon decimal and
    -- Security/WFP '0x'-hex encodings reconciled at Silver), so they join cleanly to
    -- process_correlation_bridge.raw_process_id (also BIGINT). The unmodified source text is
    -- preserved separately in *_original for audit fidelity — never overload one column with both.
    raw_process_image                                                               VARCHAR(500), -- maps to: NewProcessName | ProcessName | Application
    raw_process_id                                                                   BIGINT,       -- maps to: NewProcessId | ProcessId (normalized decimal; hex reconciled at Silver)
    raw_process_id_original                                                           VARCHAR(20),  -- maps to: original NewProcessId | ProcessId text (e.g. '0x214c'), audit only
    raw_parent_process_image                                                          VARCHAR(500), -- maps to: ParentProcessName
    raw_parent_process_id                                                              BIGINT,       -- maps to: CreatorProcessId (normalized decimal)
    raw_parent_process_id_original                                                     VARCHAR(20),  -- maps to: original CreatorProcessId text, audit only

    -- ---- Generic / lineage ----------------------------------------------------
    message_raw                                                                         TEXT,      -- maps to: Message (full text, fallback/full-text search)
    rule_name                                                                            VARCHAR(200), -- maps to: RuleName (Sysmon)
    severity                                                                              VARCHAR(10), -- maps to: Severity
    event_result                                                                           VARCHAR(20), -- maps to: EventType (INFO/AUDIT_SUCCESS/AUDIT_FAILURE/VERBOSE/DEBUG)
    opcode                                                                                  VARCHAR(20), -- maps to: Opcode

    _ingested_at                                                                             TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, -- Gold ETL load timestamp

    CONSTRAINT pk_fact_security_event PRIMARY KEY (event_sk),
    CONSTRAINT uq_fact_security_event_nk UNIQUE (source_file, hostname_nk, channel, record_number)
);

-- ---- Data-skipping / clustering strategy (FIX M6) --------------------------
-- On Delta/Iceberg-on-Parquet, B-tree secondary indexes DO NOT accelerate queries — file/
-- row-group skipping comes from partitioning + clustering/sort-order + column stats. The
-- previous CREATE INDEX statements were inert no-ops on the stated targets and are removed.
-- Apply the target-appropriate directive instead, covering the high-selectivity SOC filter
-- columns (event time, host, event type, process):
--
--   Partition (both formats): by event date derived from event_utc_time
--     Delta:   PARTITIONED BY (date_sk)            -- or a generated event_date DATE column
--     Iceberg: PARTITIONED BY days(event_utc_time) -- hidden partition transform
--
--   Cluster / sort within partitions:
--     Delta:   OPTIMIZE fact_security_event ZORDER BY (host_sk, event_utc_time, event_type_sk, process_sk);
--     Iceberg: ALTER TABLE fact_security_event WRITE ORDERED BY (host_sk, event_utc_time, event_type_sk, process_sk);
--
--   For an RDBMS deployment (Postgres/Snowflake) the original B-tree indexes ARE valid — use:
--     CREATE INDEX ix_fact_event_date     ON fact_security_event (date_sk);
--     CREATE INDEX ix_fact_event_host     ON fact_security_event (host_sk);
--     CREATE INDEX ix_fact_event_type     ON fact_security_event (event_type_sk);
--     CREATE INDEX ix_fact_event_process  ON fact_security_event (process_sk);
--     CREATE INDEX ix_fact_event_utc_time ON fact_security_event (event_utc_time);
--     CREATE INDEX ix_fact_event_logsrc   ON fact_security_event (log_source);   -- FIX M1 filter path
--     CREATE INDEX ix_fact_event_dstep    ON fact_security_event (destination_endpoint_sk);

-- ============================================================================
-- End of Gold-layer star schema DDL.
-- Next stage: medallion-architect defines Bronze (raw NDJSON, schema-on-read) and
-- Silver (typed, deduplicated on the fact natural key above, hash-parsed, ProcessGuid-
-- resolved dim_process upserts) layers that feed this Gold model.
-- ============================================================================
